highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: ""
author: Shashant Panwar

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae
title: Shashant Panwar's Resume
name: Shashant Panwar
email: shashant@panwars.com
email_full: mailto:shashant@panwars.com
website: github.io/panwars87
website_full: https://panwars87.github.io/home
github: trending
twitter: twitter
#tel: +1-2485589657
#tel_full: tel: +1-2485589657
google_maps: 'https://www.google.com/maps/place/4634+Rexwood+Dr,+Columbus,+OH+43230/'
address: 4634 Rexwood Dr.
postcode: 43230
city: Columbus 
country: United States
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
